enum AssetType {
  IMAGE
  VIDEO
}

enum OrderStatus {
  PENDING
  PROCESSING
  COMPLETED
  CANCELED
}

enum PaymentStatus {
  PENDING
  COMPLETED
  FAILED
}

enum PayoutStatus {
  PENDING
  COMPLETED
  FAILED
}

type User {
  email: String! @unique
  password: String!
  firstName: String
  lastName: String
  roles: [UserRole!] @relation
  vendor: Vendor @relation
  orders: [Order!] @relation
}

type Role {
  roleName: String! @unique
  users: [UserRole!] @relation
}

type UserRole {
  user: User! @relation
  role: Role! @relation
}

type Vendor {
  user: User! @relation
  vendorName: String! @unique
  contactEmail: String
  phoneNumber: String
  vendorProducts: [VendorProduct!] @relation
  vendorBankAccount: VendorBankAccount @relation
  balance: Float!
}

type Category {
  name: String! @unique
  products: [Product!] @relation
}

type ProductType {
  name: String! @unique
  products: [Product!] @relation
}

type Product {
  productType: ProductType! @relation
  category: Category! @relation
  name: String! @unique
  shortDescription: String!
  longDescription: String!
  vendorProducts: [VendorProduct!] @relation
  assets: [ProductAsset!] @relation
}

type VendorProduct {
  vendor: Vendor! @relation
  product: Product! @relation
  digitalKey: String!
  price: Float!
}

type Order {
  user: User! @relation
  status: OrderStatus!
  totalAmount: Float!
  orderItems: [OrderItem!] @relation
  payment: Payment @relation
}

type OrderItem {
  order: Order! @relation
  product: Product! @relation
  quantity: Int!
  price: Float!
}

type BankAccount {
  accountHolderName: String!
  bankName: String!
  accountNumber: String! @unique
  branchCode: String
  swiftCode: String
  iban: String
}

type Payment {
  order: Order! @relation
  bankAccount: BankAccount! @relation
  transactionId: String! @unique
  amount: Float!
  paymentDate: String!
  status: PaymentStatus!
}

type Payout {
  vendor: Vendor! @relation
  vendorBankAccount: VendorBankAccount! @relation
  amount: Float!
  paymentDate: String!
  status: PayoutStatus!
}

type VendorBankAccount {
  vendor: Vendor! @relation
  accountHolderName: String!
  bankName: String!
  accountNumber: String! @unique
  branchCode: String
  swiftCode: String
  iban: String
  payouts: [Payout!] @relation
}

type ProductAsset {
  product: Product! @relation
  name: String!
  url: String!
  assetType: AssetType!
}
